-- SQL SCRIPT
-- Any sql script after production 2022-04-26 here:

ALTER TABLE user_salary ADD user_create VARCHAR(32) NULL AFTER amount;
ALTER TABLE user_salary ADD user_update VARCHAR(32) NULL AFTER user_create;
ALTER TABLE user_salary ADD time_update timestamp NULL AFTER time_create;

UPDATE `user_payment_config` SET `config_flag`='1' WHERE user_id = 'sirung.t';

<<<<<<< HEAD
ALTER TABLE `permission` CHANGE `time_update` `time_update` TIMESTAMP on update CURRENT_TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `permission` CHANGE `name` `page_name` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL;
INSERT INTO `page` (`page_id`, `page_group_id`, `page_name`, `is_active`, `is_page`, `redirect`, `check_view`, `check_create_update`, `check_delete`, `check_approve`, `description`, `user_create`, `user_update`, `time_create`, `time_update`) VALUES ('P11', 'GP03', 'Report working', '1', '1', '', '1', '1', '1', '0', '', '', '', NULL, NULL)
INSERT INTO `page` (`page_id`, `page_group_id`, `page_name`, `is_active`, `is_page`, `redirect`, `check_view`, `check_create_update`, `check_delete`, `check_approve`, `description`, `user_create`, `user_update`, `time_create`, `time_update`) VALUES ('P12', 'GP05', 'Page menu', '1', '1', '', '0', '0', '0', '0', '', '', '', NULL, NULL)
INSERT INTO `page` (`page_id`, `page_group_id`, `page_name`, `is_active`, `is_page`, `redirect`, `check_view`, `check_create_update`, `check_delete`, `check_approve`, `description`, `user_create`, `user_update`, `time_create`, `time_update`) VALUES ('P13', 'GP05', 'User', '1', '1', '', '0', '0', '0', '0', '', '', '', NULL, NULL)
INSERT INTO `page` (`page_id`, `page_group_id`, `page_name`, `is_active`, `is_page`, `redirect`, `check_view`, `check_create_update`, `check_delete`, `check_approve`, `description`, `user_create`, `user_update`, `time_create`, `time_update`) VALUES ('P14', 'GP05', 'Role', '1', '1', '', '0', '0', '0', '0', '', '', '', NULL, NULL)

ALTER TABLE sys_user CHANGE user_id user_id VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
CHANGE name_th name_th VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL, 
CHANGE email email VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL, 
CHANGE phone phone VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL, 
CHANGE is_active is_active CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;




-- 20/6/2022 :
UPDATE `employee_type` SET `payment` = '0', `term` = '1', `term_day` = '30' WHERE `employee_type`.`employee_type_id` = '01';
UPDATE `employee_type` SET `payment` = '0', `term` = '1', `term_day` = '22' WHERE `employee_type`.`employee_type_id` = '02';
INSERT INTO `employee_type` (`employee_type_id`, `name`, `description`, `payment`, `term`, `term_day`, `time_create`, `time_update`, `user_create`, `user_update`) 
VALUES ('03', 'trainee', '', '1', '1', '0', '2022-06-20 10:16:31', '2022-06-20 10:16:31', NULL, NULL);

INSERT INTO `employee_type` (`employee_type_id`, `name`, `description`, `payment`, `term`, `term_day`, `time_create`, `time_update`, `user_create`, `user_update`) 
VALUES ('04', '15 day 2 times', '', '0', '2', '15', '2022-06-20 10:20:31', '2022-06-20 10:20:31', NULL, NULL);

INSERT INTO `user` (`id`, `role_id`, `department_id`, `manager_id`, `position_id`, `employee_id`, `name`, `nick_name`, `password`, `email`, `email_password`, `email_enable`, `birth_date`, `address`, `flag_search`, `start_date`, `end_date`, `work_day_start`, `work_day_end`, `work_time_start`, `work_time_end`, `latest_salary`, `edu_institute_1`, `edu_institute_2`, `edu_institute_3`, `edu_institute_4`, `edu_dur_start_1`, `edu_dur_start_2`, `edu_dur_start_3`, `edu_dur_start_4`, `edu_dur_end_1`, `edu_dur_end_2`, `edu_dur_end_3`, `edu_dur_end_4`, `edu_degree_1`, `edu_degree_2`, `edu_degree_3`, `edu_degree_4`, `enable`, `leave_quota_1`, `leave_quota_2`, `leave_quota_3`, `leave_quota_lastyear`, `time_create`, `time_update`, `email_host`, `password_update`, `login_failed`, `last_login_failed_time`, `path`, `facebookid`, `line_id`, `phone_num`, `gender`, `username`, `id_sitejob`, `title_name_th`, `title_name_en`, `name_en`, `nick_name_en`, `emergency_contact`, `emergency_phone`, `employee_type_id`, `social_security`, `withholding`, `withholding_auto`, `tax_deduction`, `transfer_type`, `bank`, `bank_type`, `bank_number`, `bank_branch`, `citizen_id`, `passport_id`) 
VALUES ('test.data1', '', NULL, NULL, NULL, NULL, 'test 1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL, '9:00', '18:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL, '0.0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, 'Mr.', 'Mr.', 'test 1', NULL, NULL, NULL, '01', '1', NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '', '');
INSERT INTO `user` (`id`, `role_id`, `department_id`, `manager_id`, `position_id`, `employee_id`, `name`, `nick_name`, `password`, `email`, `email_password`, `email_enable`, `birth_date`, `address`, `flag_search`, `start_date`, `end_date`, `work_day_start`, `work_day_end`, `work_time_start`, `work_time_end`, `latest_salary`, `edu_institute_1`, `edu_institute_2`, `edu_institute_3`, `edu_institute_4`, `edu_dur_start_1`, `edu_dur_start_2`, `edu_dur_start_3`, `edu_dur_start_4`, `edu_dur_end_1`, `edu_dur_end_2`, `edu_dur_end_3`, `edu_dur_end_4`, `edu_degree_1`, `edu_degree_2`, `edu_degree_3`, `edu_degree_4`, `enable`, `leave_quota_1`, `leave_quota_2`, `leave_quota_3`, `leave_quota_lastyear`, `time_create`, `time_update`, `email_host`, `password_update`, `login_failed`, `last_login_failed_time`, `path`, `facebookid`, `line_id`, `phone_num`, `gender`, `username`, `id_sitejob`, `title_name_th`, `title_name_en`, `name_en`, `nick_name_en`, `emergency_contact`, `emergency_phone`, `employee_type_id`, `social_security`, `withholding`, `withholding_auto`, `tax_deduction`, `transfer_type`, `bank`, `bank_type`, `bank_number`, `bank_branch`, `citizen_id`, `passport_id`) 
VALUES ('test.data2', '', NULL, NULL, NULL, NULL, 'test 2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL, '9:00', '18:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL, '0.0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, 'Mrs.', 'Mrs.', 'test 2', NULL, NULL, NULL, '02', '0', NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '', '');
INSERT INTO `user` (`id`, `role_id`, `department_id`, `manager_id`, `position_id`, `employee_id`, `name`, `nick_name`, `password`, `email`, `email_password`, `email_enable`, `birth_date`, `address`, `flag_search`, `start_date`, `end_date`, `work_day_start`, `work_day_end`, `work_time_start`, `work_time_end`, `latest_salary`, `edu_institute_1`, `edu_institute_2`, `edu_institute_3`, `edu_institute_4`, `edu_dur_start_1`, `edu_dur_start_2`, `edu_dur_start_3`, `edu_dur_start_4`, `edu_dur_end_1`, `edu_dur_end_2`, `edu_dur_end_3`, `edu_dur_end_4`, `edu_degree_1`, `edu_degree_2`, `edu_degree_3`, `edu_degree_4`, `enable`, `leave_quota_1`, `leave_quota_2`, `leave_quota_3`, `leave_quota_lastyear`, `time_create`, `time_update`, `email_host`, `password_update`, `login_failed`, `last_login_failed_time`, `path`, `facebookid`, `line_id`, `phone_num`, `gender`, `username`, `id_sitejob`, `title_name_th`, `title_name_en`, `name_en`, `nick_name_en`, `emergency_contact`, `emergency_phone`, `employee_type_id`, `social_security`, `withholding`, `withholding_auto`, `tax_deduction`, `transfer_type`, `bank`, `bank_type`, `bank_number`, `bank_branch`, `citizen_id`, `passport_id`) 
VALUES ('test.data3', '', NULL, NULL, NULL, NULL, 'test 3 ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL, '9:00', '18:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL, '0.0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, 'Ms.', 'Ms.', 'test 3', NULL, NULL, NULL, '03', '0', NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '', '');
INSERT INTO `user` (`id`, `role_id`, `department_id`, `manager_id`, `position_id`, `employee_id`, `name`, `nick_name`, `password`, `email`, `email_password`, `email_enable`, `birth_date`, `address`, `flag_search`, `start_date`, `end_date`, `work_day_start`, `work_day_end`, `work_time_start`, `work_time_end`, `latest_salary`, `edu_institute_1`, `edu_institute_2`, `edu_institute_3`, `edu_institute_4`, `edu_dur_start_1`, `edu_dur_start_2`, `edu_dur_start_3`, `edu_dur_start_4`, `edu_dur_end_1`, `edu_dur_end_2`, `edu_dur_end_3`, `edu_dur_end_4`, `edu_degree_1`, `edu_degree_2`, `edu_degree_3`, `edu_degree_4`, `enable`, `leave_quota_1`, `leave_quota_2`, `leave_quota_3`, `leave_quota_lastyear`, `time_create`, `time_update`, `email_host`, `password_update`, `login_failed`, `last_login_failed_time`, `path`, `facebookid`, `line_id`, `phone_num`, `gender`, `username`, `id_sitejob`, `title_name_th`, `title_name_en`, `name_en`, `nick_name_en`, `emergency_contact`, `emergency_phone`, `employee_type_id`, `social_security`, `withholding`, `withholding_auto`, `tax_deduction`, `transfer_type`, `bank`, `bank_type`, `bank_number`, `bank_branch`, `citizen_id`, `passport_id`) 
VALUES ('test.data4', '', NULL, NULL, NULL, NULL, 'test 4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL, '9:00', '18:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL, '0.0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, 'Ms.', 'Mr.', 'test 4', NULL, NULL, NULL, '04', '1', NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '', '');

ALTER TABLE `user_salary` CHANGE `user_salary_id` `user_salary_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
INSERT INTO `user_salary` (`user_salary_id`, `user_id`, `payment_type_id`, `amount`, `date`, `description`, `user_create`, `user_update`, `time_create`, `time_update`) VALUES (NULL, 'test.data1', 'SL', '15000.00', '2022-01-01', NULL, '', '', NULL, NULL),
(NULL, 'test.data2', 'SL', '25000.00', '2022-01-01', NULL, '', '', NULL, NULL),
(NULL, 'test.data3', 'SL', '250.00', '2022-01-01', NULL, '', '', NULL, NULL), (NULL, 'test.data4', 'SL', '40000.00', '2022-01-01', NULL, '', '', NULL, NULL);

=======
ALTER TABLE payment_type CHANGE Payment_type_name payment_type_name VARCHAR(64);
ALTER TABLE employee_type MODIFY COLUMN employee_type_id bigint(20) AUTO_INCREMENT;
>>>>>>> 46eb384515535b902725cf8ab3f7f8477ce125a7
